blank_issues_enabled: false
contact_links:
  - name: Review open issues
    url: https://github.com/vedantmgoyal2009/winget-releaser/issues
    about: Please ensure you have gone through open issues.
